#Q1

In [ ]:
list1=["aman","222",777,400.4]
tp1=tuple(list1)
print(tp1)

('aman', '222', 777, 400.4)


#Q2

In [ ]:
basic_data={'Roll no':'CB.EN.U4CSE20271','Last Name':'Yenepuri','First Name':'Ashish','Date of Birth':'19/03/02'}
for key,value in basic_data.items():
  print(key,':',value)

Roll no : CB.EN.U4CSE20271
Last Name : Yenepuri
First Name : Ashish
Date of Birth : 19/03/02


#Q3

In [ ]:
import numpy as np
np.random.seed(0)
arr=np.random.randint(0,30,size=(2,5))
print(arr)

[[12 15 21  0  3]
 [27  3  7  9 19]]


#Q4

In [ ]:
x=np.random.uniform(0.0,1.0)
print(x)
print(abs(1234))

0.6458941130666561
1234


#Q5

In [ ]:
x=np.random.randint(20,91)
print(x)

56


#Q6

In [ ]:
def ret_list(list1):
  return list1[0:3]
list1=[11,12,13,14,15]
newlist=ret_list(list1)
print(newlist)
np.random.shuffle(newlist)
print("After Shuffling :",newlist)
print(np.random.choice(list1))

[11, 12, 13]
After Shuffling : [12, 11, 13]
11


#Q7

#Q8

In [ ]:

def check_num(a):
  if a>0:
    print("If case,a is positive")
  elif a<0:
    print("Elif case,a is negetive")
  else:
    print("Else case,a is zero")
check(5)
check(-5)
check(0)
a=0
print("-----------While loop-------------")
while(a<10):
  a+=1
  if x==5:
    print("Continue when a =5")
    continue
  if a==9:
    print("break when a=9")
    break
  print(a)
print("-----------For loop---------------")

for i in range(10,20):
  if i==15:
    print("Continue when i=15")
    continue
  if i==18:
    print("break when i=18")
    break
  print(i)


#Q9

In [ ]:
phrase="The King is Dead, Long Live The King"
print(phrase)
print(phrase[0])
print(phrase[3:6])
print(phrase[3:])
print(phrase.split())

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


#Q10

In [ ]:
import numpy as np
list1=[1,4,5,8]
arr=np.array(list1)
print("The first and second element of arr",arr[0],arr[1])

The first and second element of arr 1 4


#Q11

In [ ]:
import numpy as np
two_dim=np.array([[1.,2.,3.],[4.,5.,6.]])
print("The 2D array :")
print(two_dim)

The 2D array :
[[1. 2. 3.]
 [4. 5. 6.]]


#Q12

In [ ]:
print("second row is: ",two_dim[1:][:])
print("second coloumn is: ",two_dim[:,1])
print("length of the array is: ",len(two_dim))

second row is:  [[4. 5. 6.]]
second coloumn is:  [2. 5.]
length of the array is:  2


#Q13

In [ ]:
list5=[]
for i in range(10):
  list5.append(np.random.randint(0,100))
one_dim=np.array(list5)
print("1D array: ",one_dim)
twodim=one_dim.reshape(5,2)
print("2D array: ",twodim)
print("Transpose is: ",twodim.T)

1D array:  [59 19 86 37 86 83 92 80 92 43]
2D array:  [[59 19]
 [86 37]
 [86 83]
 [92 80]
 [92 43]]
Transpose is:  [[59 86 86 92 92]
 [19 37 83 80 43]]


#Q14

In [ ]:
lis1=[1,2,3]
lis2=[4,5,6]
lis3=[7,8,9]
newarr=np.array([lis1,lis2,lis3])
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Q15

In [ ]:
arr=np.array([1,2,3])
for i in range(len(arr)):
  arr[i]=9
print(arr)


[9 9 9]


#Q16

In [ ]:
arr=np.array([2,4,5])
sum=0
for i in arr:
  sum+=i
print(sum)

11


#Q17

In [ ]:
arr=np.array([77,74,75])
prod=1
for i in arr:
  prod*=i
print(prod)

427350


#Q18

In [ ]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean is: ",np.mean(arr))
print("Varaince is: ",np.var(arr))
print("Max is:",np.max(arr))
print("Min is: ",np.min(arr))
print("Argmin is: ",np.argmin(arr))
print("Median is:",np.median(arr))
print("Argmax is: ",np.argmax(arr))
print("Standard Deviation is: ",np.std(arr))

Mean is:  12.461538461538462
Varaince is:  367.32544378698225
Max is: 56
Min is:  1
Argmin is:  1
Median is: 2.0
Argmax is:  12
Standard Deviation is:  19.165736192147232


#Q19

In [ ]:
arr=np.array([1,1,7,5,5,5,4])
uniqarr=np.array(np.unique(arr))
uniqarr.sort()
print(uniqarr)

[1 4 5 7]


#Q20

In [ ]:
p1=np.array([1,2,3])
p2=np.array([4,5,6])
print(np.dot(p1,p2))

32


#Q21

In [ ]:
a=np.array([[2,12],[2,-5]])
val,vec=np.linalg.eig(a)
print("Eigen value :",val)
print("Eigen Vector :\n",vec)

Eigen value : [ 4.52079729 -7.52079729]
Eigen Vector :
 [[ 0.97864042 -0.78338465]
 [ 0.20557951  0.6215372 ]]


#Q22

In [ ]:
a1=np.array([11,22,11,31])
a2=np.array([25,33,31,28])
corrcoef=np.corrcoef(a1,a2)
print(corrcoef)

[[1.         0.15997968]
 [0.15997968 1.        ]]
